build:
  image: node:10
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  image: node:10
  stage: test
  before_script:
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - dpkg -i google-chrome-stable_current_amd64.deb; apt-get -fy install
  script:
    - npm install --progress=false
    - npm run test -- --watch=false