build:
  image: node:10
  stage: build
  script:
    - npm install --progress=false
    - npm run build
  artifacts:
    expire_in: 1 week
    paths:
      - dist

test:
  image: node:10
  stage: test
  script:
    - npm install --progress=false
    - npm run test -- --watch=false